/**
 * sectorMap.ts — per-ticker GICS sector assignment.
 *
 * The manifest `sec` field only gives "Equities" | "Crypto" — not GICS.
 * This static map covers ~370 names (flow universe + top ~200 US liquid names
 * by market cap / flow universe membership).
 * Feed events carry a `group` field per root; that field is not yet plumbed
 * through the flow_idx payload, so we use this static map in the interim.
 * This should be superseded once the nightly manifest build injects a `gics` field.
 *
 * NOTE (display-only): sector assignments are based on GICS classification as of 2025.
 * Anything not in this map falls to "Other".
 */

import type { GicsSector } from "./types";

export const TICKER_SECTOR: Record<string, GicsSector> = {
  // ── Information Technology ──────────────────────────────────────────────────
  NVDA:  "Information Technology",
  AAPL:  "Information Technology",
  MSFT:  "Information Technology",
  AMD:   "Information Technology",
  AVGO:  "Information Technology",
  CRM:   "Information Technology",
  SMCI:  "Information Technology",
  ARM:   "Information Technology",
  MU:    "Information Technology",
  INTC:  "Information Technology",
  ORCL:  "Information Technology",
  CSCO:  "Information Technology",
  ACN:   "Information Technology",
  IBM:   "Information Technology",
  NOW:   "Information Technology",
  AMAT:  "Information Technology",
  ADI:   "Information Technology",
  KLAC:  "Information Technology",
  LRCX:  "Information Technology",
  TXN:   "Information Technology",
  QCOM:  "Information Technology",
  HPQ:   "Information Technology",
  HPE:   "Information Technology",
  DELL:  "Information Technology",
  PANW:  "Information Technology",
  FTNT:  "Information Technology",
  CRWD:  "Information Technology",
  ZS:    "Information Technology",
  OKTA:  "Information Technology",
  SNOW:  "Information Technology",
  DDOG:  "Information Technology",
  MDB:   "Information Technology",
  GTLB:  "Information Technology",
  RBLX:  "Information Technology",
  U:     "Information Technology",
  PLTR:  "Information Technology",
  MSTR:  "Information Technology",
  STX:   "Information Technology",
  WDC:   "Information Technology",
  ANET:  "Information Technology",
  JNPR:  "Information Technology",
  KEYS:  "Information Technology",
  TRMB:  "Information Technology",
  CDNS:  "Information Technology",
  SNPS:  "Information Technology",
  ANSS:  "Information Technology",
  PTC:   "Information Technology",
  EPAM:  "Information Technology",
  CTSH:  "Information Technology",
  IT:    "Information Technology",
  GPN:   "Information Technology",
  FISERV: "Information Technology",
  FIS:   "Information Technology",
  NCR:   "Information Technology",
  ADBE:  "Information Technology",
  INTU:  "Information Technology",
  APP:   "Information Technology",
  APPF:  "Information Technology",
  HUBS:  "Information Technology",
  ZM:    "Information Technology",
  DOCU:  "Information Technology",
  BOX:   "Information Technology",
  TWLO:  "Information Technology",
  FSLY:  "Information Technology",
  NET:   "Information Technology",
  CFLT:  "Information Technology",
  TEAM:  "Information Technology",
  SHOP:  "Information Technology",
  WDAY:  "Information Technology",
  SPT:   "Information Technology",
  S:     "Information Technology",
  SMAR:  "Information Technology",

  // ── Communication Services ───────────────────────────────────────────────────
  GOOGL: "Communication Services",
  GOOG:  "Communication Services",
  META:  "Communication Services",
  NFLX:  "Communication Services",
  DIS:   "Communication Services",
  CMCSA: "Communication Services",
  T:     "Communication Services",
  VZ:    "Communication Services",
  TMUS:  "Communication Services",
  CHTR:  "Communication Services",
  WBD:   "Communication Services",
  PARA:  "Communication Services",
  FOX:   "Communication Services",
  FOXA:  "Communication Services",
  SNAP:  "Communication Services",
  PINS:  "Communication Services",
  RDDT:  "Communication Services",
  SPOT:  "Communication Services",
  LYV:   "Communication Services",
  EA:    "Communication Services",
  ATVI:  "Communication Services",
  TTWO:  "Communication Services",
  MTCH:  "Communication Services",
  IAC:   "Communication Services",
  ZG:    "Communication Services",
  YELP:  "Communication Services",
  TRIP:  "Communication Services",

  // ── Consumer Discretionary ───────────────────────────────────────────────────
  AMZN:  "Consumer Discretionary",
  TSLA:  "Consumer Discretionary",
  HD:    "Consumer Discretionary",
  MCD:   "Consumer Discretionary",
  NKE:   "Consumer Discretionary",
  SBUX:  "Consumer Discretionary",
  LOW:   "Consumer Discretionary",
  TJX:   "Consumer Discretionary",
  BKNG:  "Consumer Discretionary",
  MAR:   "Consumer Discretionary",
  HLT:   "Consumer Discretionary",
  ABNB:  "Consumer Discretionary",
  GM:    "Consumer Discretionary",
  F:     "Consumer Discretionary",
  RIVN:  "Consumer Discretionary",
  LCID:  "Consumer Discretionary",
  CVNA:  "Consumer Discretionary",
  AN:    "Consumer Discretionary",
  AZO:   "Consumer Discretionary",
  ORLY:  "Consumer Discretionary",
  CMG:   "Consumer Discretionary",
  YUM:   "Consumer Discretionary",
  DPZ:   "Consumer Discretionary",
  QSR:   "Consumer Discretionary",
  DRI:   "Consumer Discretionary",
  BBY:   "Consumer Discretionary",
  TGT:   "Consumer Discretionary",
  ROST:  "Consumer Discretionary",
  ULTA:  "Consumer Discretionary",
  RH:    "Consumer Discretionary",
  W:     "Consumer Discretionary",
  ETSY:  "Consumer Discretionary",
  EBAY:  "Consumer Discretionary",
  MELI:  "Consumer Discretionary",
  PDD:   "Consumer Discretionary",
  BABA:  "Consumer Discretionary",
  JD:    "Consumer Discretionary",
  VICI:  "Real Estate",
  PHM:   "Consumer Discretionary",
  LEN:   "Consumer Discretionary",
  DHI:   "Consumer Discretionary",
  TOL:   "Consumer Discretionary",
  NVR:   "Consumer Discretionary",
  VFC:   "Consumer Discretionary",
  PVH:   "Consumer Discretionary",
  HAS:   "Consumer Discretionary",
  MAT:   "Consumer Discretionary",
  EXPE:  "Consumer Discretionary",
  LYFT:  "Consumer Discretionary",
  UBER:  "Consumer Discretionary",
  DASH:  "Consumer Discretionary",

  // ── Consumer Staples ─────────────────────────────────────────────────────────
  COST:  "Consumer Staples",
  WMT:   "Consumer Staples",
  PG:    "Consumer Staples",
  KO:    "Consumer Staples",
  PEP:   "Consumer Staples",
  PM:    "Consumer Staples",
  MO:    "Consumer Staples",
  BTI:   "Consumer Staples",
  MDLZ:  "Consumer Staples",
  KHC:   "Consumer Staples",
  GIS:   "Consumer Staples",
  K:     "Consumer Staples",
  CPB:   "Consumer Staples",
  CAG:   "Consumer Staples",
  CL:    "Consumer Staples",
  CHD:   "Consumer Staples",
  KMB:   "Consumer Staples",
  EL:    "Consumer Staples",
  COTY:  "Consumer Staples",
  SYY:   "Consumer Staples",
  KR:    "Consumer Staples",
  WBA:   "Consumer Staples",
  CVS:   "Consumer Staples",
  MNST:  "Consumer Staples",
  STZ:   "Consumer Staples",
  BUD:   "Consumer Staples",
  DEO:   "Consumer Staples",
  TAP:   "Consumer Staples",
  SAM:   "Consumer Staples",

  // ── Financials ───────────────────────────────────────────────────────────────
  JPM:   "Financials",
  BAC:   "Financials",
  WFC:   "Financials",
  GS:    "Financials",
  MS:    "Financials",
  BLK:   "Financials",
  AXP:   "Financials",
  V:     "Financials",
  MA:    "Financials",
  PYPL:  "Financials",
  SQ:    "Financials",
  AFRM:  "Financials",
  C:     "Financials",
  USB:   "Financials",
  PNC:   "Financials",
  TFC:   "Financials",
  COF:   "Financials",
  DFS:   "Financials",
  AIG:   "Financials",
  MET:   "Financials",
  PRU:   "Financials",
  ALL:   "Financials",
  PGR:   "Financials",
  TRV:   "Financials",
  CB:    "Financials",
  MMC:   "Financials",
  AON:   "Financials",
  SCHW:  "Financials",
  IBKR:  "Financials",
  STT:   "Financials",
  BK:    "Financials",
  NTRS:  "Financials",
  RJF:   "Financials",
  LFC:   "Financials",
  COIN:  "Financials",
  HOOD:  "Financials",
  MKTX:  "Financials",
  ICE:   "Financials",
  CME:   "Financials",
  CBOE:  "Financials",
  NDAQ:  "Financials",
  FDS:   "Financials",
  MSCI:  "Financials",
  SPGI:  "Financials",
  MCO:   "Financials",
  KKR:   "Financials",
  BX:    "Financials",
  APO:   "Financials",
  CG:    "Financials",
  BAM:   "Financials",
  ARES:  "Financials",

  // ── Health Care ──────────────────────────────────────────────────────────────
  LLY:   "Health Care",
  UNH:   "Health Care",
  JNJ:   "Health Care",
  PFE:   "Health Care",
  ABBV:  "Health Care",
  MRK:   "Health Care",
  BMY:   "Health Care",
  AMGN:  "Health Care",
  GILD:  "Health Care",
  BIIB:  "Health Care",
  REGN:  "Health Care",
  VRTX:  "Health Care",
  MRNA:  "Health Care",
  BNTX:  "Health Care",
  NVAX:  "Health Care",
  CI:    "Health Care",
  HUM:   "Health Care",
  MOH:   "Health Care",
  ELV:   "Health Care",
  CNC:   "Health Care",
  MDT:   "Health Care",
  BSX:   "Health Care",
  SYK:   "Health Care",
  EW:    "Health Care",
  ISRG:  "Health Care",
  ZBH:   "Health Care",
  BDX:   "Health Care",
  BAX:   "Health Care",
  HOLX:  "Health Care",
  DXC:   "Health Care",
  ILMN:  "Health Care",
  IDXX:  "Health Care",
  WAT:   "Health Care",
  TMO:   "Health Care",
  DHR:   "Health Care",
  A:     "Health Care",
  IQV:   "Health Care",
  CRL:   "Health Care",
  IQVIA: "Health Care",
  MCK:   "Health Care",
  CAH:   "Health Care",
  ABC:   "Health Care",
  HCA:   "Health Care",
  UHS:   "Health Care",
  THC:   "Health Care",

  // ── Energy ───────────────────────────────────────────────────────────────────
  XOM:   "Energy",
  CVX:   "Energy",
  COP:   "Energy",
  SLB:   "Energy",
  EOG:   "Energy",
  PXD:   "Energy",
  MPC:   "Energy",
  PSX:   "Energy",
  VLO:   "Energy",
  OXY:   "Energy",
  HES:   "Energy",
  DVN:   "Energy",
  FANG:  "Energy",
  MRO:   "Energy",
  APA:   "Energy",
  HAL:   "Energy",
  BKR:   "Energy",
  NOV:   "Energy",
  RIG:   "Energy",
  KMI:   "Energy",
  WMB:   "Energy",
  ET:    "Energy",
  MPLX:  "Energy",
  EPD:   "Energy",
  LNG:   "Energy",
  AR:    "Energy",
  EQT:   "Energy",
  RRC:   "Energy",

  // ── Industrials ──────────────────────────────────────────────────────────────
  GE:    "Industrials",
  HON:   "Industrials",
  MMM:   "Industrials",
  CAT:   "Industrials",
  DE:    "Industrials",
  BA:    "Industrials",
  RTX:   "Industrials",
  LMT:   "Industrials",
  NOC:   "Industrials",
  GD:    "Industrials",
  L3H:   "Industrials",
  HII:   "Industrials",
  TDG:   "Industrials",
  SPR:   "Industrials",
  HXL:   "Industrials",
  UPS:   "Industrials",
  FDX:   "Industrials",
  CSX:   "Industrials",
  NSC:   "Industrials",
  UNP:   "Industrials",
  ODFL:  "Industrials",
  XPO:   "Industrials",
  CHRW:  "Industrials",
  JBHT:  "Industrials",
  SAIA:  "Industrials",
  KEX:   "Industrials",
  EMR:   "Industrials",
  ETN:   "Industrials",
  PH:    "Industrials",
  ROK:   "Industrials",
  AME:   "Industrials",
  GWW:   "Industrials",
  MSC:   "Industrials",
  FAST:  "Industrials",
  IR:    "Industrials",
  TT:    "Industrials",
  LII:   "Industrials",
  JCI:   "Industrials",
  CARR:  "Industrials",
  OTIS:  "Industrials",
  XYL:   "Industrials",
  WM:    "Industrials",
  RSG:   "Industrials",
  CTAS:  "Industrials",
  ROP:   "Industrials",
  CPRT:  "Industrials",
  VRSK:  "Industrials",
  BR:    "Industrials",
  HUBB:  "Industrials",
  AXON:  "Industrials",
  SWK:   "Industrials",
  MAS:   "Industrials",

  // ── Materials ─────────────────────────────────────────────────────────────────
  LIN:   "Materials",
  APD:   "Materials",
  SHW:   "Materials",
  ECL:   "Materials",
  PPG:   "Materials",
  NEM:   "Materials",
  FCX:   "Materials",
  NUE:   "Materials",
  STLD:  "Materials",
  X:     "Materials",
  CLF:   "Materials",
  AA:    "Materials",
  CENX:  "Materials",
  PKG:   "Materials",
  IP:    "Materials",
  CF:    "Materials",
  MOS:   "Materials",
  FMC:   "Materials",
  ALB:   "Materials",
  LTHM:  "Materials",
  MP:    "Materials",

  // ── Utilities ─────────────────────────────────────────────────────────────────
  NEE:   "Utilities",
  SO:    "Utilities",
  DUK:   "Utilities",
  D:     "Utilities",
  AEP:   "Utilities",
  EXC:   "Utilities",
  PCG:   "Utilities",
  ED:    "Utilities",
  XEL:   "Utilities",
  WEC:   "Utilities",
  ES:    "Utilities",
  ETR:   "Utilities",
  CMS:   "Utilities",
  NRG:   "Utilities",
  VST:   "Utilities",
  CEG:   "Utilities",
  BE:    "Utilities",
  FCEL:  "Utilities",
  PLUG:  "Utilities",
  ENPH:  "Utilities",
  SEDG:  "Utilities",
  RUN:   "Utilities",

  // ── Real Estate ──────────────────────────────────────────────────────────────
  PLD:   "Real Estate",
  AMT:   "Real Estate",
  CCI:   "Real Estate",
  EQIX:  "Real Estate",
  PSA:   "Real Estate",
  EQR:   "Real Estate",
  AVB:   "Real Estate",
  SPG:   "Real Estate",
  O:     "Real Estate",
  WELL:  "Real Estate",
  DLR:   "Real Estate",
  IRM:   "Real Estate",
  WY:    "Real Estate",
  ARE:   "Real Estate",
  BXP:   "Real Estate",
  KIM:   "Real Estate",
  REG:   "Real Estate",
  GLPI:  "Real Estate",
  MPW:   "Real Estate",

  // ── ETFs / indices ───────────────────────────────────────────────────────────
  SPY:   "ETF",
  QQQ:   "ETF",
  IWM:   "ETF",
  DIA:   "ETF",
  SOXL:  "ETF",
  SOXS:  "ETF",
  GLD:   "ETF",
  SLV:   "ETF",
  TLT:   "ETF",
  IEF:   "ETF",
  SHY:   "ETF",
  HYG:   "ETF",
  LQD:   "ETF",
  EEM:   "ETF",
  EFA:   "ETF",
  VXX:   "ETF",
  UVXY:  "ETF",
  TQQQ:  "ETF",
  SQQQ:  "ETF",
  SPXL:  "ETF",
  SPXS:  "ETF",
  NVDL:  "ETF",
  TSLL:  "ETF",
  MSFO:  "ETF",
  XLK:   "ETF",
  XLF:   "ETF",
  XLE:   "ETF",
  XLV:   "ETF",
  XLI:   "ETF",
  XLY:   "ETF",
  XLP:   "ETF",
  XLU:   "ETF",
  XLRE:  "ETF",
  XLB:   "ETF",
  XLC:   "ETF",
  SMH:   "ETF",
  SOXX:  "ETF",
  IBB:   "ETF",
  XBI:   "ETF",
  ARK:   "ETF",
  ARKK:  "ETF",
  ARKW:  "ETF",
  ARKG:  "ETF",
  ARKF:  "ETF",
  IWF:   "ETF",
  IWD:   "ETF",
  VTI:   "ETF",
  VOO:   "ETF",
  VGT:   "ETF",
  VHT:   "ETF",
  VNQ:   "ETF",
  AMLP:  "ETF",
  BNO:   "ETF",
  USO:   "ETF",
  UNG:   "ETF",
  GDX:   "ETF",
  GDXJ:  "ETF",

  // ── Crypto ────────────────────────────────────────────────────────────────────
  "BTC-USD": "Crypto",
  "ETH-USD": "Crypto",
  "SOL-USD": "Crypto",
  "XRP-USD": "Crypto",
  "DOGE-USD": "Crypto",
  "ADA-USD": "Crypto",
  "AVAX-USD": "Crypto",
  "DOT-USD": "Crypto",
  "LINK-USD": "Crypto",
  "LTC-USD": "Crypto",
};

/** Short display label for each sector, matching the flowdesk idiom. */
export const SECTOR_LABEL: Record<GicsSector, string> = {
  "Information Technology": "TECH",
  "Communication Services": "COMM",
  "Consumer Discretionary": "CONS DISC",
  "Consumer Staples":       "STAPLES",
  "Financials":             "FINANCE",
  "Health Care":            "HEALTH",
  "Energy":                 "ENERGY",
  "Industrials":            "INDUSTRIAL",
  "Materials":              "MATERIALS",
  "Utilities":              "UTILITIES",
  "Real Estate":            "REAL EST",
  "Crypto":                 "CRYPTO",
  "ETF":                    "ETF",
  "Other":                  "OTHER",
};

/** Sector display order for grouping in the treemap. */
export const SECTOR_ORDER: GicsSector[] = [
  "Information Technology",
  "Communication Services",
  "Consumer Discretionary",
  "Consumer Staples",
  "Financials",
  "Health Care",
  "Energy",
  "Industrials",
  "Materials",
  "Utilities",
  "Real Estate",
  "Crypto",
  "ETF",
  "Other",
];

export function getSector(ticker: string): GicsSector {
  return TICKER_SECTOR[ticker] ?? "Other";
}
