/** Fail-closed display contract for Macro's private operator Issue Desk. */
export const ISSUE_DESK_SCHEMA = "options.issue_desk/v1";
export const ISSUE_LIFECYCLE = ["ISSUED", "PARTIAL_ALLOWED", "ARMED", "TRIGGERED", "MANAGED", "CLOSED", "CANCELLED", "INVALIDATED"] as const;
export type IssueLifecycleState = typeof ISSUE_LIFECYCLE[number];
export type JsonRecord = Record<string, unknown>;
const isRecord = (v: unknown): v is JsonRecord => !!v && typeof v === "object" && !Array.isArray(v);
const record = (v: unknown): JsonRecord => isRecord(v) ? v : {};
const string = (v: unknown): string | null => typeof v === "string" && v.trim() ? v.trim() : null;
const canonicalString = (v: unknown): string | null => typeof v === "string" && v.length > 0 && v.trim() === v ? v : null;
const integer = (v: unknown, min = 0): number | null => typeof v === "number" && Number.isInteger(v) && v >= min ? v : null;
const finite = (v: unknown, min = 0): number | null => typeof v === "number" && Number.isFinite(v) && v >= min ? v : null;
const positive = (v: unknown) => finite(v, Number.MIN_VALUE);
const date = (v: unknown) => {
  const s = canonicalString(v);
  if (!s || !/^\d{4}-\d{2}-\d{2}$/.test(s)) return null;
  const parsed = Date.parse(`${s}T00:00:00Z`);
  return Number.isFinite(parsed) && new Date(parsed).toISOString().slice(0, 10) === s ? s : null;
};
const utc = (v: unknown) => {
  const s = canonicalString(v); const match = s?.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?Z$/);
  if (!s || !match) return null;
  const parsed = Date.parse(s); if (!Number.isFinite(parsed)) return null;
  const d = new Date(parsed); const parts = match.slice(1).map(Number);
  return d.getUTCFullYear() === parts[0] && d.getUTCMonth() + 1 === parts[1] && d.getUTCDate() === parts[2] && d.getUTCHours() === parts[3] && d.getUTCMinutes() === parts[4] && d.getUTCSeconds() === parts[5] ? s : null;
};
const AUTHORITY_KEYS = ["may_trade", "may_rank", "may_gate", "may_size", "may_automatic"];
const authority = (v: unknown) => { const a = record(v); return exactKeys(a, AUTHORITY_KEYS) && a.may_trade === false && a.may_rank === false && a.may_gate === false && a.may_size === false && a.may_automatic === false; };
const sha = (v: unknown) => /^[a-f0-9]{64}$/.test(canonicalString(v) ?? "");
const id = (v: unknown, prefix: string) => new RegExp(`^${prefix}_[a-f0-9]{24}$`).test(canonicalString(v) ?? "") ? canonicalString(v)! : null;
const exactKeys = (v: JsonRecord, keys: string[]) => Object.keys(v).length === keys.length && keys.every((key) => Object.hasOwn(v, key));
const close = (a: number, b: number) => Math.abs(a - b) <= .000001;
const marketClose = (a: number, b: number) => Math.abs(a - b) <= .0001;
const samePortfolio = (a: PortfolioState, b: PortfolioState) => close(a.allocation_weight, b.allocation_weight) && close(a.cash_weight, b.cash_weight) && a.active_position_count === b.active_position_count;
const codes = (v: unknown) => Array.isArray(v) && v.length >= 1 && v.length <= 8 && new Set(v).size === v.length && v.every((x) => string(x)) ? v as string[] : null;
const APPROVE = new Set(["PORTFOLIO_FIT", "REGIME_ALIGNED", "EXECUTION_VERIFIED", "DIVERSIFICATION_FIT"]);
const REJECT = new Set(["ABSTAIN", "REGIME_MISMATCH", "CORRELATION_CAP", "COOLDOWN", "EVENT_RISK", "EXECUTION_MISSING", "LIQUIDITY", "NO_EDGE"]);

export interface IssueDeskProposal { proposal_id: string; proposal_revision: number; symbol: string; state: "PENDING_REVIEW" | "ISSUED" | "REJECTED"; created_at: string; available_at: string; decision_id: string | null; decision_at: string | null; receipts: JsonRecord; reason_codes: string[]; }
export interface IssueDeskDecision { decision_id: string; proposal_id: string; proposal_revision: number; proposal_symbol: string; action: "approve" | "reject"; reviewer: string; idempotency_key: string; decision_at: string; available_at: string; decision_session: string; reason_codes: string[]; resulting_state: "ISSUED" | "REJECTED"; issue_receipt: JsonRecord | null; capacity: Capacity; portfolio_before: PortfolioState; portfolio_after: PortfolioState; }
export interface IssueDeskEvent { event_id: string; state: IssueLifecycleState; decision_at: string; available_at: string; reason_codes: string[]; }
export interface IssueDeskPosition { position_id: string; proposal_id: string; proposal_revision: number; symbol: string; lifecycle_state: IssueLifecycleState; brokerage_trade: false; issue_receipt: JsonRecord; events: IssueDeskEvent[]; }
export interface Capacity { rolling_sessions: string[]; max_new_issues: 4; issued_in_window: number; remaining: number; }
interface PortfolioState { allocation_weight: number; cash_weight: number; active_position_count: number; }
export interface IssueDeskPayload { schema: typeof ISSUE_DESK_SCHEMA; authority: { may_trade: false; may_rank: false; may_gate: false; may_size: false; may_automatic: false }; authority_tier: "operator_reviewed_research_only"; mode: "private"; as_of: string; built_at: string; available_at: string; policy: JsonRecord; readiness: JsonRecord; capacity: Capacity; proposals: IssueDeskProposal[]; decisions: IssueDeskDecision[]; positions: IssueDeskPosition[]; provenance: JsonRecord; }

function capacity(v: unknown): Capacity | null {
  const c = record(v); const sessions = Array.isArray(c.rolling_sessions) ? c.rolling_sessions.map(date) : [];
  const issued = integer(c.issued_in_window); const remaining = integer(c.remaining);
  return exactKeys(c, ["max_new_issues", "rolling_sessions", "issued_in_window", "remaining"]) && c.max_new_issues === 4 && sessions.length === 3 && sessions.every((x): x is string => !!x) && new Set(sessions).size === 3 && sessions.every((session, index) => index === 0 || sessions[index - 1]! < session!) && issued != null && issued <= 4 && remaining != null && remaining === 4 - issued ? { rolling_sessions: sessions as string[], max_new_issues: 4, issued_in_window: issued, remaining } : null;
}
function portfolio(v: unknown): PortfolioState | null { const p = record(v); const allocation = finite(p.allocation_weight); const cash = finite(p.cash_weight); const active = integer(p.active_position_count); return exactKeys(p, ["allocation_weight", "cash_weight", "active_position_count"]) && allocation != null && allocation <= 1 && cash != null && cash <= 1 && active != null && close(cash, 1 - allocation) ? { allocation_weight: allocation, cash_weight: cash, active_position_count: active } : null; }
function validMacro(v: unknown): { symbol: string; value: JsonRecord } | null { const m = record(v); const symbol = canonicalString(m.asset); const targets = m.targets; const keys = ["id", "asset", "direction", "entry", "trigger", "invalidation", "targets", "option_contract", "entry_zone", "plan_asof", "recorded_at", "phase", "closed", "horizon_days", "signal_date", "price_basis_date"]; return !!(exactKeys(m, keys) && symbol && /^[A-Z0-9._-]{1,16}$/.test(symbol) && m.direction === "BULL" && string(m.id) && (m.entry === null || positive(m.entry)) && (m.trigger === null || positive(m.trigger)) && (m.invalidation === null || positive(m.invalidation)) && (targets === null || Array.isArray(targets) && targets.every(positive)) && (m.closed === null || typeof m.closed === "boolean") && (m.horizon_days === null || integer(m.horizon_days, 1))) ? { symbol, value: m } : null; }
function validContext(v: unknown, proposalAvailable: string, proposalSymbol: string): boolean {
  const c = record(v), s = record(c.source), kind = canonicalString(c.kind), status = canonicalString(s.status), sourceAvailable = s.available_at === null ? null : utc(s.available_at);
  const allowedAuthority = kind === "options_shadow" ? c.authority === "display_only" || c.authority === "unknown" : c.authority === "display_context";
  const usable = status === "available";
  const evidence = record(c.evidence), evidenceAvailable = c.evidence === null ? null : utc(evidence.available_at);
  const optionsEvidenceBound = kind !== "options_shadow" || c.evidence === null || !!sourceAvailable && !!evidenceAvailable && canonicalString(evidence.symbol) === proposalSymbol && Date.parse(evidenceAvailable) <= Date.parse(sourceAvailable);
  return !!(exactKeys(c, ["kind", "source", "authority", "evidence", "gap"]) && exactKeys(s, ["kind", "path", "status", "schema", "sha256", "as_of", "available_at"]) && kind && ["options_shadow", "vol_regime", "gex_state"].includes(kind) && s.kind === kind && canonicalString(s.path) && status && ["available", "missing", "unreadable", "root_not_object", "future_unusable", "availability_missing", "availability_invalid"].includes(status) && (s.schema === null || canonicalString(s.schema)) && (s.sha256 === null || sha(s.sha256)) && (s.as_of === null || string(s.as_of)) && (usable ? !!sourceAvailable && Date.parse(sourceAvailable) <= Date.parse(proposalAvailable) && !!s.schema && sha(s.sha256) : sourceAvailable === null && c.evidence === null) && allowedAuthority && (c.evidence === null || isRecord(c.evidence)) && optionsEvidenceBound && (c.gap === null || string(c.gap)));
}
function proposal(v: unknown, rootAvailable: string): IssueDeskProposal | null {
  const r = record(v); const proposalId = id(r.proposal_id, "oidp"); const revision = integer(r.proposal_revision, 1); const macro = validMacro(r.macro_candidate); const created = utc(r.created_at); const available = utc(r.available_at); const state = r.state;
  const decisionId = r.decision_id === undefined ? null : id(r.decision_id, "oidd"); const decisionAt = r.decision_at === undefined ? null : utc(r.decision_at);
  const source = record(r.source), execution = record(r.execution_readiness), baseKeys = ["schema", "proposal_id", "proposal_revision", "state", "created_at", "available_at", "assigned_reviewer", "source_rank", "macro_candidate", "source", "context_receipts", "execution_readiness", "authority"], terminalKeys = [...baseKeys, "decision_id", "decision_at"];
  const contextKinds = Array.isArray(r.context_receipts) ? new Set(r.context_receipts.map((x) => string(record(x).kind))) : new Set();
  if (!exactKeys(r, state === "PENDING_REVIEW" ? baseKeys : terminalKeys) || r.schema !== "options.issue_desk_proposal/v1" || !proposalId || revision == null || !macro || !created || !available || !["PENDING_REVIEW", "ISSUED", "REJECTED"].includes(String(state)) || !string(r.assigned_reviewer) || integer(r.source_rank, 1) == null || integer(r.source_rank, 1)! > 12 || !exactKeys(source, ["path", "schema", "sha256", "as_of", "available_at", "available_at_status"]) || source.path !== "site/prophet/index.json" || source.schema !== "prophet.index/v1" || !sha(source.sha256) || source.available_at !== null || source.available_at_status !== "not_available_in_current_macro_contract" || !Array.isArray(r.context_receipts) || r.context_receipts.length !== 3 || contextKinds.size !== 3 || !["options_shadow", "vol_regime", "gex_state"].every((kind) => contextKinds.has(kind)) || !r.context_receipts.every((item) => validContext(item, available, macro.symbol)) || !exactKeys(execution, ["ready", "reason"]) || execution.ready !== false || !string(execution.reason) || !authority(r.authority) || Date.parse(created) > Date.parse(available) || Date.parse(available) > Date.parse(rootAvailable)) return null;
  if (state === "PENDING_REVIEW" ? decisionId !== null || decisionAt !== null : !decisionId || !decisionAt || Date.parse(decisionAt) < Date.parse(available) || Date.parse(decisionAt) > Date.parse(rootAvailable)) return null;
  return { proposal_id: proposalId, proposal_revision: revision, symbol: macro.symbol, state: state as IssueDeskProposal["state"], created_at: created, available_at: available, decision_id: decisionId, decision_at: decisionAt, receipts: { macro_candidate: macro.value, source: record(r.source), context_receipts: r.context_receipts as JsonRecord[], execution_readiness: record(r.execution_readiness) }, reason_codes: [] };
}
function receipt(v: unknown, symbol: string, decisionAt: string, expectedCash: number): JsonRecord | null {
  const r = record(v), u = record(r.underlying), o = record(r.option), risk = record(r.risk), fit = record(r.portfolio_fit); const vals = [positive(u.reference), positive(u.trigger), positive(u.no_chase), positive(u.stop), positive(u.t1), positive(u.t2), positive(u.t1_fraction), positive(u.t2_fraction), positive(u.invalidation), positive(o.strike), integer(o.quantity, 1), positive(o.premium), positive(o.nbbo_bid), positive(o.nbbo_ask), positive(o.nbbo_mid), positive(o.spread), positive(o.spread_pct), positive(risk.allocation_weight), finite(risk.loss_at_stop_weight), finite(risk.cash_after_weight)];
  const quote = utc(o.quote_at), expiry = date(o.expiry), minHold = integer(u.minimum_hold_days, 1), horizon = integer(u.horizon_days, 1), occ = canonicalString(o.occ_symbol), occMatch = occ?.match(/^([A-Z0-9]{1,6})(\d{6})C(\d{8})$/);
  const decisionDay = `${decisionAt.slice(0, 10)}T00:00:00Z`;
  if (!exactKeys(r, ["schema", "underlying", "option", "risk", "portfolio_fit"]) || !exactKeys(u, ["reference", "trigger", "no_chase", "stop", "t1", "t2", "t1_fraction", "t2_fraction", "minimum_hold_days", "horizon_days", "starter_allowed", "add_rule", "invalidation"]) || !exactKeys(o, ["occ_symbol", "right", "strike", "expiry", "quantity", "premium", "nbbo_bid", "nbbo_ask", "nbbo_mid", "quote_at", "quote_source", "receipt_sha256", "spread", "spread_pct"]) || !exactKeys(risk, ["allocation_weight", "loss_at_stop_weight", "cash_after_weight", "disclosure"]) || !exactKeys(fit, ["regime_alignment", "sleeve", "correlation_cluster", "cooldown_clear", "event_risk_clear"]) || r.schema !== "options.issue_receipt/v1" || vals.some((x) => x == null) || minHold == null || horizon == null || horizon < minHold || !(vals[3]! < vals[0]! && vals[0]! <= vals[1]! && vals[1]! <= vals[2]! && vals[2]! < vals[4]! && vals[4]! < vals[5]!) || vals[8]! > vals[3]! || vals[6]! + vals[7]! > 1 || u.starter_allowed !== true && u.starter_allowed !== false || !string(u.add_rule) || !occMatch || occMatch[1] !== symbol || o.right !== "C" || !expiry || occMatch[2] !== expiry.replaceAll("-", "").slice(2) || Date.parse(`${expiry}T00:00:00Z`) < Date.parse(decisionDay) + minHold * 86_400_000 || !marketClose(Number(occMatch[3]) / 1000, vals[9]!) || vals[12]! > vals[14]! || vals[14]! > vals[13]! || vals[11]! < vals[12]! || vals[11]! > vals[13]! || !marketClose(vals[14]!, (vals[12]! + vals[13]!) / 2) || !marketClose(vals[15]!, vals[13]! - vals[12]!) || !marketClose(vals[16]!, vals[15]! / vals[14]!) || vals[16]! > .2 || !quote || Date.parse(quote) > Date.parse(decisionAt) || Date.parse(decisionAt) - Date.parse(quote) > 15 * 60_000 || !string(o.quote_source) || !sha(o.receipt_sha256) || vals[17]! > .25 || vals[18]! > vals[17]! || vals[19]! > 1 || !close(vals[19]!, expectedCash) || !string(risk.disclosure) || fit.regime_alignment !== "ALIGNED" || !/^[A-Za-z0-9_-]{1,32}$/.test(string(fit.sleeve) ?? "") || !/^[A-Za-z0-9_-]{1,32}$/.test(string(fit.correlation_cluster) ?? "") || fit.cooldown_clear !== true || fit.event_risk_clear !== true) return null;
  return r;
}
function decision(v: unknown, rootAvailable: string): IssueDeskDecision | null {
  const r = record(v), decisionId = id(r.decision_id, "oidd"), proposalId = id(r.proposal_id, "oidp"), revision = integer(r.proposal_revision, 1), decisionAt = utc(r.decision_at), available = utc(r.available_at), action = r.action, next = r.next_state, reasonCodes = codes(r.reason_codes), cap = capacity(r.capacity), before = portfolio(r.portfolio_state_before), after = portfolio(r.portfolio_state_after), symbol = canonicalString(r.proposal_symbol), reviewer = canonicalString(r.reviewer), idempotencyKey = canonicalString(r.idempotency_key);
  const event = record(r.event), keys = ["schema", "decision_id", "proposal_id", "proposal_revision", "action", "previous_state", "next_state", "reviewer", "decision_at", "available_at", "decision_session", "reason_codes", "idempotency_key", "request_sha256", "proposal_sha256", "proposal_symbol", "capacity", "portfolio_state_before", "portfolio_state_after", "issue_receipt", "event", "authority"];
  if (!exactKeys(r, keys) || r.schema !== "options.issue_desk_decision/v1" || !exactKeys(event, ["event_type", "post_issue_mutation"]) || !decisionId || !proposalId || revision == null || !decisionAt || !available || !symbol || !/^[A-Z0-9._-]{1,16}$/.test(symbol) || (action !== "approve" && action !== "reject") || r.previous_state !== "PENDING_REVIEW" || (next !== "ISSUED" && next !== "REJECTED") || !reviewer || !date(r.decision_session) || !reasonCodes || !idempotencyKey || !/^[A-Za-z0-9._:-]{16,128}$/.test(idempotencyKey) || !sha(r.request_sha256) || !sha(r.proposal_sha256) || !cap || !before || !after || !authority(r.authority) || event.post_issue_mutation !== false || Date.parse(decisionAt) > Date.parse(available) || Date.parse(available) > Date.parse(rootAvailable)) return null;
  const frozen = action === "approve" ? receipt(r.issue_receipt, symbol, decisionAt, after.cash_weight) : null;
  if (action === "approve" ? next !== "ISSUED" || event.event_type !== "ISSUED" || !reasonCodes.every((x) => APPROVE.has(x)) || !frozen : next !== "REJECTED" || event.event_type !== "REJECTED" || r.issue_receipt !== null || !reasonCodes.every((x) => REJECT.has(x))) return null;
  return { decision_id: decisionId, proposal_id: proposalId, proposal_revision: revision, proposal_symbol: symbol, action, reviewer, idempotency_key: idempotencyKey, decision_at: decisionAt, available_at: available, decision_session: date(r.decision_session)!, reason_codes: reasonCodes, resulting_state: next, issue_receipt: frozen, capacity: cap, portfolio_before: before, portfolio_after: after };
}
function position(v: unknown, rootAvailable: string, decisions: Map<string, IssueDeskDecision>): IssueDeskPosition | null {
  const r = record(v), positionId = id(r.position_id, "oidpos"), proposalId = id(r.proposal_id, "oidp"), revision = integer(r.proposal_revision, 1), symbol = canonicalString(r.symbol), events = r.events;
  if (!exactKeys(r, ["position_id", "proposal_id", "proposal_revision", "symbol", "lifecycle_state", "brokerage_trade", "issue_receipt", "events", "authority"]) || !positionId || !proposalId || revision == null || !symbol || !/^[A-Z0-9._-]{1,16}$/.test(symbol) || r.lifecycle_state !== "ISSUED" || r.brokerage_trade !== false || !authority(r.authority) || !Array.isArray(events) || events.length !== 1) return null;
  const e = record(events[0]), decisionId = id(e.event_id, "oidd"), decisionAt = utc(e.decision_at), available = utc(e.available_at), reasonCodes = codes(e.reason_codes), d = decisionId ? decisions.get(decisionId) : undefined;
  if (!exactKeys(e, ["event_id", "event_type", "decision_at", "available_at", "reason_codes", "reviewer", "post_issue_mutation"]) || !d || !decisionAt || !available || e.event_type !== "ISSUED" || !reasonCodes || canonicalString(e.reviewer) !== d.reviewer || e.post_issue_mutation !== false || Date.parse(decisionAt) > Date.parse(available) || Date.parse(available) > Date.parse(rootAvailable) || d.action !== "approve" || d.proposal_id !== proposalId || d.proposal_revision !== revision || d.proposal_symbol !== symbol || d.decision_at !== decisionAt || d.available_at !== available || d.reason_codes.join("|") !== reasonCodes.join("|")) return null;
  const frozen = receipt(r.issue_receipt, symbol, decisionAt, d.portfolio_after.cash_weight); if (!frozen || JSON.stringify(frozen) !== JSON.stringify(d.issue_receipt)) return null;
  return { position_id: positionId, proposal_id: proposalId, proposal_revision: revision, symbol, lifecycle_state: "ISSUED", brokerage_trade: false, issue_receipt: frozen, events: [{ event_id: decisionId!, state: "ISSUED", decision_at: decisionAt, available_at: available, reason_codes: reasonCodes }] };
}
export function normalizeIssueDeskPayload(v: unknown): IssueDeskPayload | null {
  const r = record(v), available = utc(r.available_at), built = utc(r.built_at), asOf = date(r.as_of), cap = capacity(r.capacity);
  const policy = record(r.policy), readiness = record(r.readiness), provenance = record(r.provenance);
  if (!exactKeys(r, ["schema", "authority", "authority_tier", "mode", "as_of", "built_at", "available_at", "policy", "readiness", "proposals", "decisions", "positions", "capacity", "provenance"]) || !exactKeys(policy, ["max_new_issues", "rolling_sessions", "max_issue_allocation_weight", "max_active_per_sleeve", "max_active_per_correlation_cluster", "zero_is_valid", "automatic_authority", "post_issue_mutation_v1"]) || !exactKeys(readiness, ["issuance_requires", "current_options_shadow_authority", "brokerage_execution"]) || !exactKeys(provenance, ["durable_private_store", "snapshot", "public_r2_mirror"]) || r.schema !== ISSUE_DESK_SCHEMA || r.mode !== "private" || r.authority_tier !== "operator_reviewed_research_only" || !authority(r.authority) || !asOf || !built || !available || Date.parse(built) > Date.parse(available) || !cap || cap.rolling_sessions[2] !== asOf || policy.max_new_issues !== 4 || policy.rolling_sessions !== 3 || policy.max_issue_allocation_weight !== .25 || policy.max_active_per_sleeve !== 2 || policy.max_active_per_correlation_cluster !== 1 || policy.zero_is_valid !== true || policy.automatic_authority !== false || policy.post_issue_mutation_v1 !== false || readiness.issuance_requires !== "complete_operator_attested_issue_receipt" || readiness.current_options_shadow_authority !== "display_only" || readiness.brokerage_execution !== false || provenance.durable_private_store !== true || !isRecord(provenance.snapshot) || provenance.public_r2_mirror !== false || !Array.isArray(r.proposals) || !Array.isArray(r.decisions) || !Array.isArray(r.positions)) return null;
  const proposals = r.proposals.map((x) => proposal(x, available)); const decisions = r.decisions.map((x) => decision(x, available));
  if (proposals.some((x) => !x) || decisions.some((x) => !x)) return null;
  const ps = proposals as IssueDeskProposal[], ds = decisions as IssueDeskDecision[]; if (new Set(ps.map((x) => x.proposal_id)).size !== ps.length || new Set(ds.map((x) => x.decision_id)).size !== ds.length || new Set(ds.map((x) => x.proposal_id)).size !== ds.length || new Set(ds.map((x) => x.idempotency_key)).size !== ds.length) return null;
  const decisionMap = new Map(ds.map((x) => [x.decision_id, x])); const proposalMap = new Map(ps.map((x) => [x.proposal_id, x]));
  let priorDecision = -Infinity, priorAvailable = -Infinity; const priorIssues: IssueDeskDecision[] = [];
  for (const d of ds) {
    const p = proposalMap.get(d.proposal_id), decisionMs = Date.parse(d.decision_at), availableMs = Date.parse(d.available_at);
    if (!p || p.proposal_revision !== d.proposal_revision || p.symbol !== d.proposal_symbol || p.state !== d.resulting_state || p.decision_id !== d.decision_id || p.decision_at !== d.decision_at || decisionMs < Date.parse(p.available_at) || decisionMs < priorDecision || availableMs < priorAvailable || d.capacity.rolling_sessions[2] !== d.decision_session) return null;
    const issuedBeforeWindow = priorIssues.filter((prior) => d.capacity.rolling_sessions.includes(prior.decision_session)).length;
    const expectedIssued = issuedBeforeWindow + (d.action === "approve" ? 1 : 0);
    const allocationBefore = priorIssues.reduce((sum, prior) => sum + Number(record(record(prior.issue_receipt).risk).allocation_weight), 0);
    const expectedBefore = { allocation_weight: allocationBefore, cash_weight: 1 - allocationBefore, active_position_count: priorIssues.length };
    const allocationAfter = allocationBefore + (d.action === "approve" ? Number(record(record(d.issue_receipt).risk).allocation_weight) : 0);
    const expectedAfter = { allocation_weight: allocationAfter, cash_weight: 1 - allocationAfter, active_position_count: priorIssues.length + (d.action === "approve" ? 1 : 0) };
    const fit = record(record(d.issue_receipt).portfolio_fit), priorFits = priorIssues.map((prior) => record(record(prior.issue_receipt).portfolio_fit));
    if (d.capacity.issued_in_window !== expectedIssued || !samePortfolio(d.portfolio_before, expectedBefore) || !samePortfolio(d.portfolio_after, expectedAfter) || d.action === "approve" && (priorIssues.some((prior) => prior.proposal_symbol === d.proposal_symbol) || priorFits.filter((prior) => prior.sleeve === fit.sleeve).length >= 2 || priorFits.some((prior) => prior.correlation_cluster === fit.correlation_cluster))) return null;
    if (d.action === "approve") priorIssues.push(d);
    priorDecision = decisionMs; priorAvailable = availableMs;
  }
  const positions = r.positions.map((x) => position(x, available, decisionMap)); if (positions.some((x) => !x)) return null; const pos = positions as IssueDeskPosition[];
  const issuedInRootWindow = ds.filter((d) => d.resulting_state === "ISSUED" && cap.rolling_sessions.includes(d.decision_session)).length;
  if (new Set(pos.map((x) => x.position_id)).size !== pos.length || pos.some((x) => { const p = proposalMap.get(x.proposal_id); return !p || p.state !== "ISSUED" || p.proposal_revision !== x.proposal_revision || p.symbol !== x.symbol; }) || ds.filter((d) => d.resulting_state === "ISSUED").length !== pos.length || cap.issued_in_window !== issuedInRootWindow) return null;
  return { schema: ISSUE_DESK_SCHEMA, authority: r.authority as IssueDeskPayload["authority"], authority_tier: "operator_reviewed_research_only", mode: "private", as_of: asOf, built_at: built, available_at: available, policy, readiness, capacity: cap, proposals: ps, decisions: ds, positions: pos, provenance };
}
