"use client";
/**
 * SignalCard — one row in the Prophet signal stream (left pane).
 *
 * Collapsed shows: ticker, BULL/BEAR badge, archetype tag, entry, days active,
 * live-vs-plan P&L (if last_price present), T1-progress bar, min-hold bar with
 * lock icon, phase chip.
 *
 * Expanded reveals: OptionCard sub-card.
 *
 * HONESTY DOCTRINE:
 *   - BULL/BEAR are engine-assigned direction labels — not recommendations.
 *   - Phase chip is descriptive lifecycle state.
 *   - P&L is live-vs-plan — labeled "vs plan" to avoid implying realized.
 *   - No "validated", no predictive copy.
 */

import { useState } from "react";
import { makeProphetT } from "./prophetStrings";
import { OptionCard } from "./OptionCard";
import type { OptionContractPayload } from "./OptionCard";
import type { Lang } from "@/lib/i18n";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface PlanSummary {
  id: string;
  asset: string;
  direction: "BULL" | "BEAR";
  /** signal archetype tag e.g. "Resumption", "Recovery" */
  archetype?: string | null;
  entry: number | null;
  targets: number[];
  invalidation: number | null;
  horizon_days: number | null;
  min_hold_days: number | null;
  /**
   * ISO date string for when the plan was issued.
   * Nested-shape payloads use `asof`; flat-shape payloads (current prod) use
   * `_signal_date`. Both are accepted — consumers should call planAsof(plan).
   */
  asof?: string | null;
  _signal_date?: string | null;
  option_contract: OptionContractPayload | null;
  /**
   * Nested management state (legacy shape).
   * Current flat shape hoists management_confidence / phase / recommended_action
   * to the plan top-level. Both shapes are accepted.
   */
  state?: {
    phase?: string | null;
    management_confidence?: number | null;
    recommended_action?: string | null;
    geometry?: {
      dist_to_stop_r?: number | null;
      dist_to_t1_r?:   number | null;
      horizon_pct_used?: number | null;
    } | null;
  } | null;
  /** Flat-shape: management confidence at top level (0–100) */
  management_confidence?: number | null;
  /** Flat-shape: lifecycle phase at top level */
  phase?: string | null;
  /** Flat-shape: recommended action at top level */
  recommended_action?: string | null;
  /** Last price from payload (optional — may be absent) */
  last_price?: number | null;
  /**
   * What-to-do-now bullets (optional — generated by content engine).
   * List of 2-3 numbered action strings keyed to current phase.
   * Graceful fallback: block hidden when absent.
   */
  what_to_do_now?: string[] | null;
  /** ZH variant of what_to_do_now (optional — present when engine emits zh blocks). */
  what_to_do_now_zh?: string[] | null;
  /**
   * Profit-taking plan rows (optional — generated by content engine).
   * Each row: {level: number|null, label: string, action: string, status: "ACTIVE"|"PENDING"|"DONE"}
   * Graceful fallback: block hidden when absent.
   */
  profit_plan?: Array<{
    level: number | null;
    label: string;
    action: string;
    status: "ACTIVE" | "PENDING" | "DONE";
  }> | null;
  /** ZH variant of profit_plan rows (same shape, zh action strings). */
  profit_plan_zh?: Array<{
    level: number | null;
    label: string;
    action: string;
    status: "ACTIVE" | "PENDING" | "DONE";
  }> | null;
  /** Machine-generated thesis prose (+ zh variant when the engine emits one). */
  thesis?: string | null;
  thesis_zh?: string | null;
  /** Flat-shape origination fields the payload already carries (display only). */
  _conviction_score?: number | null;
  _r_unit?: number | null;
  trigger?: number | null;
}

/** Return ISO date string from either flat (_signal_date) or nested (asof) shape. */
export function planAsof(plan: PlanSummary): string {
  return plan._signal_date ?? plan.asof ?? "";
}

/** Return management_confidence from either flat or nested shape. */
export function planConfidence(plan: PlanSummary): number | null {
  return plan.management_confidence ?? plan.state?.management_confidence ?? null;
}

/** Return lifecycle phase from either flat or nested shape. */
export function planPhase(plan: PlanSummary): string | null {
  return plan.phase ?? plan.state?.phase ?? null;
}

/** Return recommended_action from either flat or nested shape. */
export function planRecommendedAction(plan: PlanSummary): string | null {
  return plan.recommended_action ?? plan.state?.recommended_action ?? null;
}

interface SignalCardProps {
  plan: PlanSummary;
  lang: Lang;
  selected: boolean;
  onSelect: (plan: PlanSummary) => void;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function daysActive(asof: string): number {
  const issued = new Date(asof).getTime();
  // Math.max(0, NaN) === NaN — guard explicitly so a missing/invalid date
  // never propagates NaN into the rendered string.
  if (!Number.isFinite(issued)) return 0;
  const now = Date.now();
  return Math.max(0, Math.floor((now - issued) / 86_400_000));
}

function t1Progress(entry: number | null, t1: number | null, last: number | null, isBear: boolean): number | null {
  if (entry == null || t1 == null || last == null) return null;
  if (isBear) {
    // BEAR: progress is downward (entry→t1 = entry−t1 total; entry−last = so far)
    const total = entry - t1;
    const done  = entry - last;
    if (total <= 0) return null;
    return Math.max(0, Math.min(100, (done / total) * 100));
  }
  const total = t1 - entry;
  const done  = last - entry;
  if (total <= 0) return null;
  return Math.max(0, Math.min(100, (done / total) * 100));
}

/** One token per archetype — `.obs-tag` derives fill and ring from it. */
function archetypeColor(tag: string): string {
  const t = tag.toLowerCase();
  if (t === "resumption") return "var(--warn)";
  if (t === "recovery")   return "var(--brand-2)";
  if (t === "breakout")   return "var(--ai)";
  return "var(--muted)";
}

/**
 * Lifecycle-phase tint, shared by every Prophet surface that shows a phase chip
 * (this card, the analysis header, the confidence panel) so one state never wears
 * three colours. Directional states ride --up/--down and flip with data-updown.
 *
 *   pre_trigger      → muted     (armed, nothing has happened)
 *   triggered_pre_t1 → brand-2   (live, working)
 *   at_t1/T1→T2/T2   → up        (at or past target)
 *   overtime         → warn      (past its horizon — caution, not direction)
 *   invalidated      → down      (thesis broken)
 */
export function phaseTone(phase: string | null | undefined): string {
  if (!phase) return "var(--text-2)";
  if (phase === "invalidated") return "var(--down)";
  if (phase === "overtime") return "var(--warn)";
  if (phase.includes("t1") || phase.includes("t2")) {
    return phase === "triggered_pre_t1" ? "var(--brand-2)" : "var(--up)";
  }
  if (phase === "pre_trigger") return "var(--muted)";
  return "var(--text-2)";
}

// ── Component ──────────────────────────────────────────────────────────────────

export function SignalCard({ plan, lang, selected, onSelect }: SignalCardProps) {
  const t = makeProphetT(lang);
  const [expanded, setExpanded] = useState(false);

  const isBear  = plan.direction === "BEAR";
  const t1      = plan.targets?.[0] ?? null;
  const days    = daysActive(planAsof(plan));
  const t1pct   = t1Progress(plan.entry, t1, plan.last_price ?? null, isBear);

  // Min-hold bar
  const minHold = plan.min_hold_days ?? null;
  const minPct  = minHold != null && minHold > 0
    ? Math.min(100, (days / minHold) * 100)
    : null;
  const isLocked    = minPct != null && minPct < 100;
  const holdLabel   = isLocked ? t("locked") : t("eligible");
  const holdColor   = isLocked ? "var(--muted)" : "var(--up)";

  // P&L vs plan
  let pnlPct: number | null = null;
  if (plan.last_price != null && plan.entry != null && plan.entry > 0) {
    const raw = (plan.last_price - plan.entry) / plan.entry * 100;
    pnlPct = isBear ? -raw : raw;
  }

  // Phase chip — supports both flat (plan.phase) and nested (plan.state?.phase) shapes
  const currentPhase = planPhase(plan);
  const phaseMap: Record<string, string> = {
    pre_trigger:       t("phasePretrigger"),
    triggered_pre_t1:  t("phaseTriggered"),
    at_t1:             t("phaseAtT1"),
    between_t1_t2:     t("phaseBetweenT1T2"),
    at_t2:             t("phaseAtT2"),
    overtime:          t("phaseOvertime"),
    invalidated:       t("phaseInvalidated"),
  };
  const phaseDisplay = currentPhase ? (phaseMap[currentPhase] ?? currentPhase) : null;
  const isInvalidated = currentPhase === "invalidated";
  const phaseColor = phaseTone(currentPhase);

  const dirColor = isBear ? "var(--down)" : "var(--up)";

  return (
    <div
      className={`obs-card obs-prophet-signal${selected ? " sel" : ""}${isInvalidated ? " dead" : ""}`}
      style={{ "--c": phaseColor } as React.CSSProperties}
      onClick={() => onSelect(plan)}
      role="option"
      aria-selected={selected}
    >
      {/* Line 1: ticker + direction … age */}
      <div className="obs-prophet-sig-hd">
        <span className="obs-prophet-sig-tkr">{plan.asset}</span>
        <span
          className="obs-tag obs-prophet-sig-dir"
          style={{ "--c": dirColor } as React.CSSProperties}
        >
          {isBear ? `▼ ${t("bear")}` : `▲ ${t("bull")}`}
        </span>
        <span className="obs-prophet-sig-age num">{days}{t("daysActive")}</span>
      </div>

      {/* Line 2: entry level + archetype … lifecycle phase */}
      <div className="obs-prophet-sig-sub">
        <span className="obs-prophet-sig-entry">
          <i>{t("entryLabel")}</i>
          <b className="num">{plan.entry != null ? `$${plan.entry.toFixed(2)}` : "—"}</b>
        </span>
        {plan.archetype && (
          <span
            className="obs-tag obs-prophet-sig-arch"
            style={{ "--c": archetypeColor(plan.archetype) } as React.CSSProperties}
          >
            {plan.archetype}
          </span>
        )}
        {pnlPct != null && (
          <span
            className="obs-prophet-sig-pnl num"
            style={{ "--c": pnlPct >= 0 ? "var(--up)" : "var(--down)" } as React.CSSProperties}
          >
            {pnlPct >= 0 ? "+" : ""}{pnlPct.toFixed(1)}%
            <i>{lang === "zh" ? "对比计划" : "vs plan"}</i>
          </span>
        )}
        {phaseDisplay && (
          <span
            className="obs-tag obs-prophet-sig-phase"
            style={{ "--c": phaseColor } as React.CSSProperties}
          >
            {phaseDisplay}
          </span>
        )}
      </div>

      {/* T1 progress — only exists when the payload carries a last price */}
      {t1pct != null && (
        <div className="obs-prophet-sig-bar">
          <div className="obs-prophet-sig-bar-hd">
            <span className="num">{t1pct.toFixed(0)}% {t("t1Progress")}</span>
          </div>
          <div className="obs-prophet-meter">
            <div className="obs-prophet-meter-fill up" style={{ width: `${t1pct}%` }} />
          </div>
        </div>
      )}

      {/* Min-hold bar */}
      {minPct != null && (
        <div className="obs-prophet-sig-bar">
          <div className="obs-prophet-sig-bar-hd">
            <span className="num">{days}d / {minHold}d {t("minHold")}</span>
            <span style={{ color: holdColor }}>{isLocked ? "🔒 " : ""}{holdLabel}</span>
          </div>
          <div className="obs-prophet-meter">
            <div
              className={`obs-prophet-meter-fill${isLocked ? "" : " up"}`}
              style={{ width: `${minPct}%` }}
            />
          </div>
        </div>
      )}

      {/* Expand toggle for OptionCard */}
      {plan.option_contract && (
        <button
          className="obs-prophet-sig-exp"
          onClick={(e) => { e.stopPropagation(); setExpanded((v) => !v); }}
          aria-expanded={expanded}
          aria-label={expanded ? t("optionCollapse") : t("optionExpand")}
        >
          {expanded ? "▲" : "▼"}
        </button>
      )}

      {/* OptionCard sub-card (expanded) */}
      {expanded && plan.option_contract && (
        <OptionCard contract={plan.option_contract} lang={lang} />
      )}
    </div>
  );
}
