// R3 OI-suite fixtures + f-param routing (Structure tab).
//
// The fixture family was GENERATED by running the macro engine
// (engine/options_hub compute_oi_time/compute_max_pain/compute_oi_change) over
// synthetic deterministic chains, so schema and math are faithful by
// construction — these tests lock that property against hand-edits:
//   1. ROUTING. backendPath/r2Key for the four new f-params — a mis-resolved
//      key fails silently (R2 fall-through → null → honest-empty UI), so the
//      mapping is pinned exactly (the surface-store lesson).
//   2. ENTRY INTEGRITY. Root-keyed entries renderable under their own key
//      (StructureView guards on payload.root === selection); curve minima sit
//      AT the published max_pain; ΔOI arithmetic is internally exact.
//   3. HONESTY MARKERS. Every payload discloses oi_date "t-1" (the timing law
//      every panel repeats), d_oi_pct is null exactly when oi_prev is 0, and
//      the cross-root board is magnitude-ranked (reductions survive).
import { describe, it, expect } from "vitest";
import { promises as fs } from "fs";
import path from "path";
import { backendPath, fixtureFor, isValidF, r2Key } from "@/lib/flowSource";

const dataFile = (name: string) => path.join(process.cwd(), "public", "data", name);
const loadJson = async <T>(name: string) =>
  JSON.parse(await fs.readFile(dataFile(name), "utf8")) as Record<string, T>;

interface OiTimeEntry {
  schema: string; asof: string; root: string; oi_date: string;
  history: { date: string; call_oi: number; put_oi: number; total_oi: number }[];
  coverage: { n_days: number; since: string | null };
}
interface MaxPainEntry {
  schema: string; asof: string; root: string; spot_ref: number; oi_date: string;
  expiries: {
    exp: string; dte: number; max_pain: number; call_oi: number; put_oi: number;
    curve?: { strike: number; call_value_mn: number; put_value_mn: number; value_mn: number }[];
  }[];
  expiries_full_n: number;
  by_strike: { strike: number; call_oi: number; put_oi: number }[];
  by_strike_full_n: number;
}
interface OiChangeEntry {
  schema: string; asof: string; scope: string; oi_date: string;
  root?: string; prev_session?: string | null; roots_n?: number;
  rows: {
    root: string; right: string; exp: string; dte: number; strike: number;
    oi: number; oi_prev: number; d_oi: number; d_oi_pct: number | null; mid: number | null;
  }[];
}

describe("R3 OI-suite f-param routing", () => {
  it("validates the four new forms and only those shapes", () => {
    for (const f of ["oi_time:SPY", "max_pain:SPY", "oi_change", "oi_change:SPY"]) {
      expect(isValidF(f), f).toBe(true);
    }
    // Bare prefixes without a root are refused; `oi` stays the oi_movers feed.
    for (const f of ["oi_time:", "max_pain:", "oi_change:"]) {
      expect(isValidF(f), f).toBe(false);
    }
    expect(isValidF("oi")).toBe(true);
  });

  it("pins the backend paths + R2 keys exactly (silent-fallthrough hazard)", () => {
    expect(backendPath("oi_time:SPY")).toBe("/api/hub/oi_time/SPY");
    expect(backendPath("max_pain:SPY")).toBe("/api/hub/max_pain/SPY");
    expect(backendPath("oi_change")).toBe("/api/hub/oi_change");
    expect(backendPath("oi_change:SPY")).toBe("/api/hub/oi_change/SPY");
    expect(r2Key("oi_time:SPY")).toBe("options_hub/oi_time/SPY.json");
    expect(r2Key("max_pain:SPY")).toBe("options_hub/max_pain/SPY.json");
    expect(r2Key("oi_change")).toBe("options_hub/oi_change.json");
    expect(r2Key("oi_change:SPY")).toBe("options_hub/oi_change/SPY.json");
    // The pre-existing exact-match feed must be untouched by the new prefixes.
    expect(r2Key("oi")).toBe("options_hub/oi_movers.json");
  });

  it("serves per-root payloads case-normalized and the cross board for bare oi_change", async () => {
    const spy = (await fixtureFor("oi_time:SPY")) as unknown as OiTimeEntry;
    expect(spy.root).toBe("SPY");
    expect(await fixtureFor("oi_time:spy")).toEqual(spy);
    const cross = (await fixtureFor("oi_change")) as unknown as OiChangeEntry;
    expect(cross.scope).toBe("cross_root");
  });
});

describe("oi_time fixture — entry integrity", () => {
  it("entries are keyed by their own root, dated ascending, and sum exactly", async () => {
    const all = await loadJson<OiTimeEntry>("oi_time_fixture.json");
    expect(Object.keys(all)).toContain("SPY");
    expect(Object.keys(all)).toContain("QQQ");
    for (const [key, e] of Object.entries(all)) {
      expect(e.root, key).toBe(key);
      expect(e.schema, key).toBe("options_hub.oi_time/v1");
      expect(e.oi_date, key).toBe("t-1");
      expect(e.history.length, key).toBeGreaterThanOrEqual(10);
      for (let i = 0; i < e.history.length; i++) {
        const r = e.history[i];
        expect(r.total_oi, `${key} ${r.date}`).toBe(r.call_oi + r.put_oi);
        if (i > 0) expect(r.date > e.history[i - 1].date, `${key} asc ${r.date}`).toBe(true);
      }
      expect(e.coverage.n_days, key).toBe(e.history.length);
      expect(e.coverage.since, key).toBe(e.history[0].date);
    }
  });
});

describe("max_pain fixture — entry integrity", () => {
  it("curve minima sit AT the published max_pain, and the argmin strike is always drawable", async () => {
    const all = await loadJson<MaxPainEntry>("max_pain_fixture.json");
    expect(Object.keys(all)).toContain("SPY");
    for (const [key, e] of Object.entries(all)) {
      expect(e.root, key).toBe(key);
      expect(e.schema, key).toBe("options_hub.max_pain/v1");
      expect(e.oi_date, key).toBe("t-1");
      expect(Number.isFinite(e.spot_ref), key).toBe(true);
      expect(e.expiries.length, key).toBeGreaterThan(0);
      expect(e.expiries_full_n, key).toBeGreaterThanOrEqual(e.expiries.length);
      let withCurve = 0;
      for (const row of e.expiries) {
        expect(row.dte, `${key} ${row.exp} dte`).toBeGreaterThan(0);
        if (!row.curve) continue;
        withCurve++;
        const strikes = row.curve.map((c) => c.strike);
        expect(strikes.includes(row.max_pain), `${key} ${row.exp} argmin drawable`).toBe(true);
        const min = row.curve.reduce((m, c) => (c.value_mn < m.value_mn ? c : m), row.curve[0]);
        expect(min.strike, `${key} ${row.exp} curve argmin == max_pain`).toBe(row.max_pain);
        for (const c of row.curve) {
          // Published totals must be the sum of the published legs (2dp rounding).
          expect(Math.abs(c.value_mn - (c.call_value_mn + c.put_value_mn)), `${key} ${row.exp} ${c.strike}`)
            .toBeLessThanOrEqual(0.011);
        }
      }
      expect(withCurve, `${key} at least one curve`).toBeGreaterThan(0);
      // by_strike ladder: sorted ascending, non-negative legs, disclosed cut.
      expect(e.by_strike.length, key).toBeGreaterThan(2);
      expect(e.by_strike_full_n, key).toBeGreaterThanOrEqual(e.by_strike.length);
      for (let i = 0; i < e.by_strike.length; i++) {
        const r = e.by_strike[i];
        expect(r.call_oi, `${key} ${r.strike}`).toBeGreaterThanOrEqual(0);
        expect(r.put_oi, `${key} ${r.strike}`).toBeGreaterThanOrEqual(0);
        if (i > 0) expect(r.strike, `${key} asc`).toBeGreaterThan(e.by_strike[i - 1].strike);
      }
    }
  });
});

describe("oi_change fixture — entry integrity + the cross board", () => {
  it("per-root rows are magnitude-ranked with exact ΔOI arithmetic", async () => {
    const all = await loadJson<OiChangeEntry>("oi_change_fixture.json");
    for (const [key, e] of Object.entries(all)) {
      if (key === "cross") continue;
      expect(e.root, key).toBe(key);
      expect(e.schema, key).toBe("options_hub.oi_change/v1");
      expect(e.scope, key).toBe("root");
      expect(e.oi_date, key).toBe("t-1");
      expect(typeof e.prev_session, key).toBe("string");
      expect(e.rows.length, key).toBeGreaterThan(0);
      for (let i = 0; i < e.rows.length; i++) {
        const r = e.rows[i];
        expect(r.root, `${key} row root`).toBe(key);
        expect(r.d_oi, `${key} ${r.exp} ${r.strike}${r.right}`).toBe(r.oi - r.oi_prev);
        expect(r.d_oi_pct == null, `${key} pct-null iff new`).toBe(r.oi_prev === 0);
        expect(r.dte, `${key} upcoming only`).toBeGreaterThan(0);
        if (i > 0) {
          expect(Math.abs(r.d_oi), `${key} magnitude-ranked`)
            .toBeLessThanOrEqual(Math.abs(e.rows[i - 1].d_oi));
        }
      }
    }
  });

  it("the cross board merges every root magnitude-ranked (reductions survive)", async () => {
    const all = await loadJson<OiChangeEntry>("oi_change_fixture.json");
    const cross = all["cross"];
    expect(cross.scope).toBe("cross_root");
    expect(cross.oi_date).toBe("t-1");
    const roots = new Set(cross.rows.map((r) => r.root));
    expect(roots.size).toBeGreaterThanOrEqual(2);
    let sawNegative = false;
    for (let i = 0; i < cross.rows.length; i++) {
      if (cross.rows[i].d_oi < 0) sawNegative = true;
      if (i > 0) {
        expect(Math.abs(cross.rows[i].d_oi))
          .toBeLessThanOrEqual(Math.abs(cross.rows[i - 1].d_oi));
      }
    }
    expect(sawNegative, "a reduction must survive the cut").toBe(true);
  });
});
